### PR TITLE
Adding User()->getCount()

### PR DESCRIPTION
**Pull request by kublermdk**
Adding a getCount() function for Users.

Currently the ['meta']['total'] information is discarded by the PHP SDK and there's no easy way of knowing the total number of users. This returns just the total.

### CODE REVIEW

**Comment by NinoSkopac** [comment]
Thank you for these. 

I can't cherry pick or merge these commits because:
a) filenames have changed 
b) we now _do_ have `token_auths` in Token()
c) it now _is_ possible to get user meta via `PromisePay::getMeta()`

**Comment by NinoSkopac** [comment]
I do think that it would make sense to have helpers functions like "getUsersCount" and "getItemsCount", and that's why I am going to create an issue regarding helper methods for 3.0.

**Comment by NinoSkopac** [comment]
Just added in 3.0's devel branch: https://github.com/NinoSkopac/promisepay-php/commit/6d18cf2358914c2c88bb557388852f04c18e7041#diff-f0b815b43a505d9b25f8d625f7748af9

**Comment by kublermdk** [comment]
Thank you!

**Pull request closed without merging**
